### PR TITLE
Use .NET Standard instead of .NET Framework

### LINKED ISSUE #84: Internal debugger error on latest dnspy net48 commit...
Before clicking `Submit new issue`, try the latest build [](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
6.1.9 commit 4.033
ide

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Just breakpoints debugger on Module .cctor on simple winform app.... only for net48 dnspy release

### PR DESCRIPTION
**Pull request by mobile46**
Fixes #84

### CODE REVIEW

**Comment by ElektroKill** [comment]
Hi, thanks for the PR. However, could you please provide more info on why this change is appropriate? On the surface, it makes little sense to me as to why changing the target framework would fix the issue (keep in mind I'm unable to reproduce this issue on my primary system as well as various virtual machines). The Roslyn NuGet packages are compatible with both .NET Framework and .NET Core so there should not be a compatibility problem.

If you would be able to provide me with information on how could I reproduce the issue or why the issue occurs in the first place, that would make it much easier to determine the appropriate fix.

Finally, please rebase your changes onto the current master branch so that there are no unnecessary merge commits in the PR :)

**Comment by mobile46** [comment]
Because some packages that using by projects like Microsoft.CodeAnalysis.Features, Microsoft.CodeAnalysis.CSharp etc. supports only .net core 3.1 and .net standard 2.0. I thought changing the framework might fix this issue and looks like these changes fixes that issue.

Btw when I tried the latest build I faced this issue I don't know how to reproduce it.

**Comment by ElektroKill** [comment]
> Because some packages that using by projects like Microsoft.CodeAnalysis.Features, Microsoft.CodeAnalysis.CSharp etc. supports only .net core 3.1 and .net standard 2.0.

.NET Framework 4.8, as well as .NET 6, are compatible with .NET Standard 2.0 so I have no idea why there would be a problem caused by it. 🤔
I will do more research into this bug as I have never seen something similar before. I really hope there is a better way to solve this because this fix looks more like a hacky fix :P

**Comment by mobile46** [comment]
Windows 10 IoT Enterprise LTSC 21H2 build 19044.1288

```
C:\Users\MoFoSiX>dotnet --list-sdks
5.0.407 [C:\Program Files\dotnet\sdk]
6.0.201 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]

C:\Users\MoFoSiX>dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by ElektroKill** [comment]
Hi, will changing only the ExpressionCompiler project to `netstandard2.0` fix the issue for you? I would prefer to change as little in regards to target runtimes as possible. :)

**Comment by mobile46** [comment]
Hi, it's not working but this commit contains little changes as possible :)

**Review by ElektroKill — APPROVED** [review]

**Comment by Deltafox79** [comment]
> @Deltafox79 Could you verify that this PR fixes the problem you have been facing?

Yes is ok for me...

**Pull request merged**
