### PR TITLE
Update images to VS2022 catalogue

### PR DESCRIPTION
**Pull request by InKahootz**
See corresponding dnSpy.Images PR [here](https://github.com/dnSpyEx/dnSpy.Images/pull/1).

VS2022 has refreshed their image catalogue. It's still in preview and subject to change but I doubt there will be major changes. I will keep on eye on it or we can just keep this PR open until 2022 comes out of preview.

With the refresh to the images, I also took the time to refresh the dnSpy icon. I did a few prototypes/color schemes (I could not for the life of me find the original font that 0xd4d used in the x86 icon). The x64 remains all white, while the x86 has a red indicator.

I used the Assembly.xaml and changed the colors and generated some png and ico. 

These are transparent backgrounds. My XAML viewer is the dark grey you see.
x64:
image

x86:
image

### CODE REVIEW

**Comment by InKahootz** [comment]
Comparison screenshot
Current (left) vs Proposed (right)

image

**Comment by ElektroKill** [comment]
Wow, that must have taken some time to do! I will keep this PR open in case Microsoft does some last-minute icon changes and merge it when VS 2022 is officially released. As for the x86 logo I'm undecided on which one we should use. Other than that I see no issues or problems!

**Review by ElektroKill — APPROVED** [review]

**Comment by InKahootz** [comment]
Updated images for 17.0.0 Preview 3.

Looks like they will be making a few minor adjustments to the images. I'll keep updating with each preview.
:warning: I'll be amending and force pushing to keep both repos at just 1 commit. So be careful to anyone who checks these out. ⚠️

**Comment by InKahootz** [comment]
Updated for 17.0.0-preview.4

**Comment by InKahootz** [comment]
No changes in RC2 (Preview 6), RC3 (Preview 7).
Should be close to being locked in.

**Comment by ElektroKill** [comment]
Hi, sorry for the rather late reply. I think I would like to stick with the x86 icon featuring the "32" text in the corner (the last option you presented). I will be merging the two pull requests right after the x86 icon is updated :) 
Thanks for the contribution :p

**Comment by InKahootz** [comment]
No worries. I will get this PR updated shortly.

You can actually go ahead and merge the submodule PR b/c the actual dnSpy and dnSpyx86 icons are in this repo and not part of dnSpy.Images. That'll allow me to also point the submodule to the right hash after the dnSpy.Images repo is updated.

**Comment by InKahootz** [comment]
@ElektroKill Updated. Do a hard reset if you checked out locally since I force pushed.

**Comment by ElektroKill** [comment]
Merged :tada:

**Comment by Nuklon** [comment]
Just gonna post it here, the new explorer icons are not very good, as it's white on a white application...

**Comment by ElektroKill** [comment]
> Just gonna post it here, the new explorer icons are not very good, as it's white on a white application...

As someone that uses dark mode on Windows I didn't have a problem with this but launching dnSpy on a light mode system definitely shows the problem. Can you open a new issue? Let's not hijack old pull requests :)

**Pull request merged**
