### PR TITLE
Update Roslyn to 4.10 (refs #40)

### PR DESCRIPTION
**Pull request by ElektroKill**
This PR aims at updating the Roslyn version used by dnSpy from version 2.10 to version 4.10 bringing support for modern language features for the `Edit Code` actions, `C# Interactive` tool window. This update also brings all the other improvements and bug fixes made to the compiler to dnSpy for a better experience when debugging, editing code, and using the C# interactive tool. This update will also allow us to use later versions of ILSpy to decompile newer language features which can be later consumed by the newer Roslyn version.

Currently, according to my limited testing, all features of dnSpy work well when using the new Roslyn version. There are only some minor things left to improve.
- [x] The Roslyn projects from dnSpy used mixed code style which looks awful when browsing on GitHub.
- [x] The editor features powered by Roslyn use rather old code taken from the Roslyn 2.10 source code. These features should be updated for the more modern Roslyn versions. Examples of such features: QuickInfo, SmartIndent, and SignatureHelp.
- [x] Update license information, Roslyn is now licensed under MIT.

There are currently no CI builds available for this branch. If anyone would like to test it just clone the branch and compile dnSpy yourself. Any issues discovered with these new changes should be posted below after verifying that they are not present in the latest stable release.

### CODE REVIEW

**Comment by jogibear9988** [comment]
maybe the roslynpad nugets could be used for the editor features...

**Comment by ElektroKill** [comment]
> maybe the roslynpad nugets could be used for the editor features...

I don't think this is possible due to how tightly the integration works currently. The code copied from Roslyn has to be modified to some degree to work with dnSpy. In the future, I might look into changing how this works but that would be a very big breaking change that I want to avoid for the small number of extension developers out there.

**Comment by jogibear9988** [comment]
Roslynpad uses another nuget, so internal classes from roslyn could be used. Maybe this would help.

**Comment by ElektroKill** [comment]
Hi, RoslynPad has a package called RoslynPad.Roslyn which exposes some of the internal classes of Roslyn, however that selection of classes is nowhere near enough to satisfy what dnSpy needs to access. dnSpy needs access to other classes for components like the ExpressionCompiler, as well as other tight integrations. It would be nice to be able to use the nuget package but I don’t think we should use the nuget combined with the other hack already in place to expose Roslyn classes. The nuget package from RoslynPad actually uses a very similar trick to gain access to internal classes as we use currently.

**Pull request merged**
