### PR TITLE
build.ps1: Add R2R

### PR DESCRIPTION
**Pull request by imba-tjd**
This will decrease the startup time

### CODE REVIEW

**Comment by ElektroKill** [comment]
Hi! the code you modified is used to build the AppHostPatcher project which is used during the build process and is not included in the final release. Was this intentional?

**Comment by imba-tjd** [comment]
No :joy:

**Comment by imba-tjd** [comment]
Shall I modify this?

```
	if ($NoMsbuild) {
		dotnet publish -v:m -c $configuration -f $net_tfm -r $rid --self-contained
		if ($LASTEXITCODE) { exit $LASTEXITCODE }
	}
	else {
		msbuild -v:m -m -restore -t:Publish -p:Configuration=$configuration -p:TargetFramework=$net_tfm -p:RuntimeIdentifier=$rid -p:SelfContained=True
		if ($LASTEXITCODE) { exit $LASTEXITCODE }
	}
```

**Comment by ElektroKill** [comment]
Yes that is the part responsible for building the actual project and not a build utility :)

**Pull request closed without merging**
